@startuml
actor User as A
participant UI
participant System as S
participant "WebSocket" as W
participant "Certificate Authority" as CA
S->UI:Mostra notifica  di richiesta chat
alt Accetta
A->UI:Accetta la richiesta
UI->S:Invia la richiesta
S->S:Genera coppia chiavi PU\PR
S->S:Genera session id
S->W:Stabilisci la connessione
W-->S:Conessione stabilita
S->W:Invia chiave pubblica con il session id
W-->S:Riceve la chiave pubblica con il session id
S->CA:Verifica chiave pubblica
CA-->S:Restuisci verifica
alt PU invalida
S->W:Chiudi connessione
W->S:Connessione terminata
else
S->S:Genera la chiave di sessione
S->W:Chiave di sessione generata
W-->S:Conferma chiave di sessione generata
loop non viene interrotta

end
W->S:Ricevi messaggio di richiesta cifrato
S->S:Decifra il messaggio ( usando session key)
S->UI:Mostra il messaggio di richiesta
UI->S:Rispondi al messaggio
S->S: Cifra il messaggio( usando Session key)
S->W:Invia il messaggio( inserendo session id)
end
end
@enduml