@startuml
'https://plantuml.com/activity-diagram-beta


if(starting) then (yes)
if(pharmacist is empty) then(yes)
stop
note right: return empty
else (no)
if(pharmacist is present & chat is empty)then(yes)
stop
note right:return pharmacist
else
:Check pharmacist that not joined;
:Random pharmacist;
stop
note right:return pharmacist
endif
endif
else (chatting)
if(pharmacist) then (yes)
:Retrieve pharmacist into list of one map of seller key;
:Send message;
else(Seller)
:Retrieve seller into
endif



@enduml

