@startuml

skinparam classAttributeIconSize 0

class DetailDao {
  + DetailDao(Database):
  - table_name: String
  + findById(Integer): FieldData
  # setUpdateParameter(PreparedStatement, FieldData): void
  # setDeleteParameter(PreparedStatement, FieldData): void
  # setFindByIdParameters(PreparedStatement, Integer): void
  # mapRow(ResultSet): FieldData
  # setInsertParameter(PreparedStatement, FieldData): void
   findQueryAll: String
   insertQuery: String
   deletequery: String
   updatequery: String
   table_name: String
}
class FarmaciaDao {
  + FarmaciaDao(Database):
  # setFindByIdParameters(PreparedStatement, Integer): void
  # setUpdateParameter(PreparedStatement, FieldData): void
  # setDeleteParameter(PreparedStatement, FieldData): void
  # mapRow(ResultSet): FieldData
  # setInsertParameter(PreparedStatement, FieldData): void
  + buildQueryasParameter(String): String
   insertQuery: String
   deletequery: String
   updatequery: String
}
class FarmacoDao {
  + FarmacoDao(Database):
  # setDeleteParameter(PreparedStatement, FieldData): void
  # setFindByIdParameters(PreparedStatement, Integer): void
  + findByLikeName(String): List<FieldData>
  # mapRow(ResultSet): FieldData
  + findByName(String): List<FieldData>
  # setUpdateParameter(PreparedStatement, FieldData): void
  # setInsertParameter(PreparedStatement, FieldData): void
   findQueryAll: String
   insertQuery: String
   deletequery: String
   updatequery: String
}
interface GenericDaoAble<T, ID> << interface >> {
  + insert(T): boolean
  + findById(ID): T
  + findAll(): List<T>
  + update(T): boolean
  + delete(T): boolean
}
class GenericJDBCDao<T, ID> {
  + GenericJDBCDao(String, Database):
  + findByParameter(String, int): List<T>
  + update(T): boolean
  # setUpdateParameter(PreparedStatement, T): void
  + findByParameters(String, Object[]): List<T>
  + commit(): void
  + insert(T): boolean
  # mapRow(ResultSet): T
  # setFindByIdParameters(PreparedStatement, ID): void
  + rollback(): void
  + insertAndReturnID(T): int
  # setDeleteParameter(PreparedStatement, T): void
  + delete(T): boolean
  + findAll(): List<T>
  - switch_type(PreparedStatement, Object, int): void
  + findById(ID): T
  + findAllWithExecutionTime(): List<String>
  # setInsertParameter(PreparedStatement, T): void
  + findByParameter(String, String): List<T>
  + findByParametersExists(String, Object[]): boolean
   findQueryAll: String
   findAllExecutionTime: String
   insertQuery: String
   deletequery: String
   updatequery: String
   transaction: boolean
}
class InfoSocietyDao {
  + InfoSocietyDao(Database):
  # setFindByIdParameters(PreparedStatement, Integer): void
  # setDeleteParameter(PreparedStatement, FieldData): void
  # setInsertParameter(PreparedStatement, FieldData): void
  # setUpdateParameter(PreparedStatement, FieldData): void
  # mapRow(ResultSet): FieldData
   insertQuery: String
   deletequery: String
   updatequery: String
}
class LotAssigmentDao {
  + LotAssigmentDao(Database):
  + findQuantitybyFarmacoId(int): List<FieldData>
  + findByFarmacoAll(): List<FieldData>
  + findFarmacoQuantity(int): List<FieldData>
  # setInsertParameter(PreparedStatement, LotAssigment): void
  + findExistsAssigment(int, String): boolean
  # setDeleteParameter(PreparedStatement, LotAssigment): void
  # setUpdateParameter(PreparedStatement, LotAssigment): void
  # setFindByIdParameters(PreparedStatement, Integer): void
  + findExistAndReturnId(int, String): int
  + findPharmaHousebyLotCode(String): List<FieldData>
  # mapRow(ResultSet): LotAssigment
   insertQuery: String
   findAllExecutionTime: String
   deletequery: String
   updatequery: String
}
class LotAssigmentShelvesDao {
  + LotAssigmentShelvesDao(Database):
  + findByLots(String): List<ShelvesAssigment>
  # setDeleteParameter(PreparedStatement, ShelvesAssigment): void
  + findByWarehouse(int): List<ShelvesAssigment>
  - mapRowFind(ResultSet): FieldData
  # setInsertParameter(PreparedStatement, ShelvesAssigment): void
  # setFindByIdParameters(PreparedStatement, Integer): void
  # mapRow(ResultSet): ShelvesAssigment
  + findbyLotCode(String): List<FieldData>
  + findbyShelfCode(String): List<FieldData>
  # setUpdateParameter(PreparedStatement, ShelvesAssigment): void
   insertQuery: String
   deletequery: String
   updatequery: String
}
class LotDimensionDao {
  + LotDimensionDao(Database):
  # setInsertParameter(PreparedStatement, LotDimensionModel): void
  # setFindByIdParameters(PreparedStatement, String): void
  # setDeleteParameter(PreparedStatement, LotDimensionModel): void
  + findByLots(String, int): Optional<LotDimensionModel>
  # mapRow(ResultSet): LotDimensionModel
  # setUpdateParameter(PreparedStatement, LotDimensionModel): void
   insertQuery: String
   deletequery: String
   updatequery: String
}
class LottiDao {
  + LottiDao(Database, String):
  # setFindByIdParameters(PreparedStatement, Integer): void
  # mapRow(ResultSet): FieldData
  + buildQueryasParameterSearch(String): String
  + findBySearch(String, String): List<FieldData>
  + FindByFarmacoNameHaveLot(): List<String>
  # setDeleteParameter(PreparedStatement, FieldData): void
  # setInsertParameter(PreparedStatement, FieldData): void
  + findLotsbyPharma(int): List<FieldData>
  + findbyDate(int): List<FieldData>
  + findByIds(int, String): Optional<FieldData>
  + findByFarmaco(int): List<FieldData>
  # setUpdateParameter(PreparedStatement, FieldData): void
  + findByLottoCode(String): List<FieldData>
  + findLotsByFarmacoName(String): List<String>
   findQueryAll: String
   insertQuery: String
   deletequery: String
   updatequery: String
}
class MagazzinoDao {
  + MagazzinoDao(Database):
  # setInsertParameter(PreparedStatement, WarehouseModel): void
  # setUpdateParameter(PreparedStatement, WarehouseModel): void
  # mapRow(ResultSet): WarehouseModel
  # setFindByIdParameters(PreparedStatement, Integer): void
  # setDeleteParameter(PreparedStatement, WarehouseModel): void
   insertQuery: String
   deletequery: String
   updatequery: String
}
class MagazzinoModelDao {
  + MagazzinoModelDao(ShelfDao, ShelvesDao, MagazzinoDao):
   fullWarehouseModel: List<WarehouseModel>
}
class PharmaDao {
  + PharmaDao(Database):
  # setInsertParameter(PreparedStatement, FieldData): void
  + findAllName(): List<FieldData>
  # setUpdateParameter(PreparedStatement, FieldData): void
  # setDeleteParameter(PreparedStatement, FieldData): void
  # mapRow(ResultSet): FieldData
  # setFindByIdParameters(PreparedStatement, Integer): void
   findQueryAll: String
   insertQuery: String
   deletequery: String
   updatequery: String
}
class PromotionDao {
  + PromotionDao(Database):
  # setFindByIdParameters(PreparedStatement, Integer): void
  # mapRow(ResultSet): FieldData
  # setDeleteParameter(PreparedStatement, FieldData): void
  # setUpdateParameter(PreparedStatement, FieldData): void
  # setInsertParameter(PreparedStatement, FieldData): void
   findQueryAll: String
   insertQuery: String
   deletequery: String
   updatequery: String
   productNoPromotionActive: List<FieldData>
}
class PurchaseCreditNoteDao {
  + PurchaseCreditNoteDao(Database):
  + findDetailbyInvoiceId(int): List<FieldData>
  + exist_credit_note(int): boolean
  # mapRow(ResultSet): FieldData
  # setUpdateParameter(PreparedStatement, FieldData): void
  # setFindByIdParameters(PreparedStatement, Integer): void
  + findbyInvoiceid(int): FieldData
  # setInsertParameter(PreparedStatement, FieldData): void
  # setDeleteParameter(PreparedStatement, FieldData): void
   findQueryAll: String
   insertQuery: String
   deletequery: String
   updatequery: String
}
class PurchaseCreditNoteDetailDao {
  + PurchaseCreditNoteDetailDao(Database):
  # setFindByIdParameters(PreparedStatement, Integer): void
  # setUpdateParameter(PreparedStatement, FieldData): void
  # setInsertParameter(PreparedStatement, FieldData): void
  + findDetailbyCreditNoteId(int): List<FieldData>
  # mapRow(ResultSet): FieldData
  # setDeleteParameter(PreparedStatement, FieldData): void
   findQueryAll: String
   insertQuery: String
   deletequery: String
   updatequery: String
}
class PurchaseInvoiceDao {
  + PurchaseInvoiceDao(Database):
  # setUpdateParameter(PreparedStatement, FieldData): void
  # mapRow(ResultSet): FieldData
  # setFindByIdParameters(PreparedStatement, Integer): void
  # setInsertParameter(PreparedStatement, FieldData): void
  # setDeleteParameter(PreparedStatement, FieldData): void
   findQueryAll: String
   insertQuery: String
   deletequery: String
   updatequery: String
}
class PurchaseOrderDao {
  + PurchaseOrderDao(Database):
  # setInsertParameter(PreparedStatement, FieldData): void
  + findAllWithInvoiceIdNullByPharmaId(int): List<FieldData>
  # setUpdateParameter(PreparedStatement, FieldData): void
  + findbyPharmaHousebyInvoiceID(int): String
  # setFindByIdParameters(PreparedStatement, String): void
  # setDeleteParameter(PreparedStatement, FieldData): void
  + findByInvoiceid(int): List<FieldData>
  # mapRow(ResultSet): FieldData
   findQueryAll: String
   insertQuery: String
   deletequery: String
   updatequery: String
}
class PurchaseOrderDetailDao {
  + PurchaseOrderDetailDao(Database):
  # setInsertParameter(PreparedStatement, FieldData): void
  # setDeleteParameter(PreparedStatement, FieldData): void
  + findByProductPrice(int): List<FieldData>
  # mapRow(ResultSet): FieldData
  # setUpdateParameter(PreparedStatement, FieldData): void
  + findDetailbyPurchaseOrderId(int): List<FieldData>
  # setFindByIdParameters(PreparedStatement, Integer): void
  + findAllReportData(): List<FieldData>
   findQueryAll: String
   insertQuery: String
   deletequery: String
   updatequery: String
}
class SellerCreditNoteDao {
  + SellerCreditNoteDao(Database):
  # setDeleteParameter(PreparedStatement, FieldData): void
  # setFindByIdParameters(PreparedStatement, Integer): void
  # setInsertParameter(PreparedStatement, FieldData): void
  # mapRow(ResultSet): FieldData
  # setUpdateParameter(PreparedStatement, FieldData): void
   insertQuery: String
   deletequery: String
   updatequery: String
}


DetailDao                    -[#000082,plain]-^  GenericJDBCDao
FarmaciaDao                  -[#000082,plain]-^  GenericJDBCDao
FarmacoDao                   -[#000082,plain]-^  GenericJDBCDao
GenericJDBCDao               -[#008200,dashed]-^  GenericDaoAble
InfoSocietyDao               -[#000082,plain]-^  GenericJDBCDao
LotAssigmentDao              -[#000082,plain]-^  GenericJDBCDao
LotAssigmentShelvesDao       -[#000082,plain]-^  GenericJDBCDao
LotDimensionDao              -[#000082,plain]-^  GenericJDBCDao
LottiDao                     -[#000082,plain]-^  GenericJDBCDao
MagazzinoDao                 -[#000082,plain]-^  GenericJDBCDao
PharmaDao                    -[#000082,plain]-^  GenericJDBCDao
PromotionDao                 -[#000082,plain]-^  GenericJDBCDao
PurchaseCreditNoteDao        -[#000082,plain]-^  GenericJDBCDao
PurchaseCreditNoteDetailDao  -[#000082,plain]-^  GenericJDBCDao
PurchaseInvoiceDao           -[#000082,plain]-^  GenericJDBCDao
PurchaseOrderDao             -[#000082,plain]-^  GenericJDBCDao
PurchaseOrderDetailDao       -[#000082,plain]-^  GenericJDBCDao
SellerCreditNoteDao          -[#000082,plain]-^  GenericJDBCDao

@enduml
